spring.application.name=core-app

server.port = 7777

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/spo-db
spring.datasource.username=postgres
spring.datasource.password=Aradhya123*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true